import type { ComponentLibraryItem } from "../types/field.types";

export const COMPONENT_LIBRARY: ComponentLibraryItem[] = [
  {
    type: "text",
    title: "Text Input",
    description: "Single line text field",
    category: "basic",
    icon: "Type",
  },
  {
    type: "number",
    title: "Number Input",
    description: "Numeric value field",
    category: "basic",
    icon: "Hash",
  },
  {
    type: "textarea",
    title: "Text Area",
    description: "Multi-line text field",
    category: "basic",
    icon: "AlignLeft",
  },
  {
    type: "date",
    title: "Date Picker",
    description: "Date selection field",
    category: "basic",
    icon: "Calendar",
  },
  {
    type: "dropdown",
    title: "Dropdown",
    description: "Select from options",
    category: "selection",
    icon: "ChevronDown",
  },
  {
    type: "radio",
    title: "Radio Group",
    description: "Single choice selection",
    category: "selection",
    icon: "CircleDot",
  },
  {
    type: "checkbox",
    title: "Checkbox Group",
    description: "Multiple choice selection",
    category: "selection",
    icon: "CheckSquare",
  },
  {
    type: "result",
    title: "Result Field",
    description: "Lab test result value",
    category: "lab",
    icon: "FlaskConical",
  },
  {
    type: "unit",
    title: "Unit Field",
    description: "Measurement unit",
    category: "lab",
    icon: "Ruler",
  },
  {
    type: "reference-range",
    title: "Reference Range",
    description: "Normal value ranges",
    category: "lab",
    icon: "ArrowLeftRight",
  },
  {
    type: "critical-value",
    title: "Critical Value",
    description: "Critical alert thresholds",
    category: "lab",
    icon: "AlertTriangle",
  },
  {
    type: "formula",
    title: "Formula Field",
    description: "Calculated result field",
    category: "lab",
    icon: "Calculator",
  },
  {
    type: "table",
    title: "Table",
    description: "Structured data table",
    category: "advanced",
    icon: "Table",
  },
  {
    type: "rich-text",
    title: "Rich Text Editor",
    description: "Formatted text content",
    category: "advanced",
    icon: "FileText",
  },
  {
    type: "image",
    title: "Image",
    description: "Image placeholder",
    category: "advanced",
    icon: "Image",
  },
  {
    type: "barcode",
    title: "Barcode",
    description: "Barcode display",
    category: "advanced",
    icon: "Barcode",
  },
  {
    type: "qrcode",
    title: "QR Code",
    description: "QR code display",
    category: "advanced",
    icon: "QrCode",
  },
  {
    type: "signature",
    title: "Signature",
    description: "Digital signature field",
    category: "advanced",
    icon: "PenLine",
  },
];

export const COMPONENT_CATEGORIES = [
  { id: "basic", label: "Basic Fields" },
  { id: "selection", label: "Selection Fields" },
  { id: "lab", label: "Lab Specific Fields" },
  { id: "advanced", label: "Advanced Components" },
] as const;

export const FIELD_TYPE_LABELS: Record<string, string> = {
  text: "Text",
  number: "Number",
  textarea: "Text Area",
  date: "Date",
  dropdown: "Dropdown",
  radio: "Radio Group",
  checkbox: "Checkbox Group",
  result: "Result",
  unit: "Unit",
  "reference-range": "Reference Range",
  "critical-value": "Critical Value",
  formula: "Formula",
  table: "Table",
  "rich-text": "Rich Text",
  image: "Image",
  barcode: "Barcode",
  qrcode: "QR Code",
  signature: "Signature",
};
